### PR TITLE
Fix file upload

### LINKED ISSUE #266: Upload not Working
When uploading a file on iOS its uploaded to the Bucket, but it does not show up after uploading.

This long entry is not triggered: Notifying the file backend.

### PR DESCRIPTION
**Pull request by JonasWanke**
**Closes: #266**

- File upload wasn't working due to query parameters provided to our `NetworkService` via the URL i/o the `queryParameters` map. `NetworkService` now accepts parameters in either of them.
- The error wasn't logged. We now have `SnackBarService.performMultiAction` with an automatic update & failure handling.
- `AssertionError`s are automatically logged at `Level.wtf`.
- Logged messages with `level >= Level.error` are sent to Sentry in production.

### CODE REVIEW

File: lib/app/error_reporting.dart [hunk 1]
```diff
@@ -22,41 +23,64 @@ Future<void> runWithErrorReporting(Future<void> Function() body) async {
...
 }
 
-bool get _isInDebugMode {
+bool get isInDebugMode {
   bool inDebugMode = false;
   assert(inDebugMode = true);
   return inDebugMode;
 }
 
+const _logerLevelToSentryLevel = {
```
Comment (MarcelGarus) [inline lib/app/error_reporting.dart]:
```suggestion
const _loggerLevelToSentryLevel = {
```

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

**Review by MarcelGarus — APPROVED** [review]

**Comment by janrenz** [comment]
Works well on iOS too
