### PR TITLE
Show internal assets in content WebViews

### LINKED ISSUE #99: Internal assets aren't loaded inside content WebViews
**To Reproduce**
1. Login (e.g. as example teacher)
2. Go to courses
3. Select a course (e.g. "Biologie 10b")
4. Select a topic (e.g. "Das (menschliche) Auge")

**Expected behavior**
Add the auth header and load images/etc. correctly.

The old android app intercepted all requests and added the auth header if required: https://github.com/schul-cloud/schulcloud-mobile-android/blob/76115f13942d62ee2169021e6390bfd57b52a55f/app/src/main/java/org/schulcloud/mobile/views/ContentWebView.kt#L113-L139, https://github.com/schul-cloud/schulcloud-mobile-android/blob/76115f13942d62ee2169021e6390bfd57b52a55f/app/src/main/java/org/schulcloud/mobile/utils/WebUtils.kt#L33-L40

**Screenshots**
<table><tr><td>App <td>Website
<tr><td> <td> </table>

### PR DESCRIPTION
**Pull request by JonasWanke**
**Fixes: #99**

**Changes**

We now show assets in lesson content that can only be accessed by signed-in users by setting a JWT-cookie.

Other notable changes:
- Prevent crash when signing out after the session already expired.
- Set minimum log level to `debug`.
- Sort lessons by their `position` field and show/hide lessons and contents based on their `hidden` field.

### CODE REVIEW

File: lib/course/widgets/lesson_screen.dart [hunk 1]
```diff
@@ -83,7 +81,7 @@ class _LessonScreenState extends State<LessonScreen> {
         }
 
         final lesson = update.data;
-        // TODO(marcelgarus): use FancyScaffold when flutter_cached supports slivers
+        final firstContent = lesson.contents.where((c) => c.isVisible).first;
```
Comment (MarcelGarus) [inline lib/course/widgets/lesson_screen.dart]:
```suggestion
        final firstContent = lesson.contents.firstWhere((c) => c.isVisible);
```
Also, what if there is no content for this lesson? Throwing an error is probably not the right thing to do…

File: lib/course/widgets/lesson_screen.dart [hunk 2]
```diff
@@ -115,47 +123,46 @@ class _LessonScreenState extends State<LessonScreen> {
 
   void _showLessonContentMenu(BuildContext context, Lesson lesson) {
     context.showFancyModalBottomSheet(
+      useRootNavigator: true,
       builder: (context) => Column(
         mainAxisSize: MainAxisSize.min,
         children: [
-          for (final content in lesson.contents)
+          for (final content in lesson.contents.where((c) => c.isVisible))
```
Comment (MarcelGarus) [inline lib/course/widgets/lesson_screen.dart]: Maybe even create a getter for `visibleContents` and one on the `Course` for `visibleLessons`? Seems like the `.where(…)` call is used a lot in this code.

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

File: lib/course/widgets/lesson_screen.dart (hunk 2 above)
Comment (JonasWanke) [reply lib/course/widgets/lesson_screen.dart]: What's the recommended way to do this for lessons within a course?
- Create a second `LazyIds<Lesson>` only containing visible lessons
- Create a getter `CacheController<List<Lesson>> get visibleLessons => lessons.controller.map(…)`

File: lib/course/widgets/lesson_screen.dart (hunk 1 above)
Comment (JonasWanke) [reply lib/course/widgets/lesson_screen.dart]: For now we show a button to view this lesson in the browser (and hope the user selects to open this link in a browser and not in our app).
In the future, we should improve this → #236

**Comment by janrenz** [comment]
In the future we could consider this plugin: https://pub.dev/packages/webview_flutter

**Comment by JonasWanke** [comment]
@janrenz We were using that plugin in the beginning but had to change to a fork because its (white) background can't be made transparent (very noticeable in dark mode; flutter/flutter#29300). We then discovered [`flutter_inappwebview`](https://pub.dev/packages/flutter_inappwebview) which has a lot more features making both a web-based sign-in easier and viewing internal assets possible.

File: lib/course/widgets/lesson_screen.dart (hunk 2 above)
Comment (MarcelGarus) [reply lib/course/widgets/lesson_screen.dart]: I would probably choose the latter one because then there's a single source of truth about how to query the API.
In other cases, where the API provides some more efficient way to only query the desired items, I'd, of course, go with the first one.

**Review by MarcelGarus — APPROVED** [review]

File: lib/course/widgets/lesson_screen.dart (hunk 2 above)
Comment (JonasWanke) [reply lib/course/widgets/lesson_screen.dart]: Okay, I went with the first option. `/lessons?hidden[$ne]=true`
