### PR TITLE
Fix caching

### LINKED ISSUE #125: Caching does not work offline
**Describe the bug**
In airplane mode, instead of relying on the cache, the app just reports the error that no connection to the server could be made.

**To Reproduce**
1. Turn off Wifi and mobile data
2. Start the app and navigate to any page that loads data from the API

### PR DESCRIPTION
**Pull request by MarcelGarus**
Fixes #125 
Finally fixes the caching. 🎉

Before merging, this should be addressed:

- [x] merge with the master branch
- [x] wait for [this Hive issue](https://github.com/hivedb/hive/issues/245) to be resolved

### CODE REVIEW

**Comment by MarcelGarus** [comment]
The caching is disabled for now (just a few lines commented out in `app/hive.dart`). We'll wait for the Hive issue to get resolved, then we'll have another look at this.
This PR shifts the CRUD responsibilities from BLoCs to data classes which makes for much cleaner code. That's why we decided to merge this PR nevertheless. By merging, there's also one branch less that we need to keep up-to-date with the master.

**Comment by janrenz** [comment]
OK, so lets get this merged. Maybe we can move the caching behavior to a config var, this could also help during developing of API based stuff

**Comment by janrenz** [comment]
And why don't we fix the issue in Hive in a branch (use the branch, make a PR and go back to the Hive master once its fixed)

File: lib/app/chip.dart [hunk 1]
```diff
@@ -11,9 +11,6 @@ class ChipGroup extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
-    return Wrap(
-      spacing: 8,
-      children: children,
-    );
+    return Wrap(spacing: 8, children: children);
```
Comment (JonasWanke) [inline lib/app/chip.dart]: Why remove the formatting? This isn't related to this PR

File: lib/app/services/storage.dart [hunk 2]
```diff
@@ -1,50 +1,56 @@
...
+
+  // The token is a JWT token. JWT tokens consist of a header, body and claim
+  // (signature), all separated by dots and encoded in base64. For now, we
+  // don't verify the claim, but just decode the body.
+  Id<User> get currentUserId {
+    final token = this.token.getValue();
+    final encodedBody = token.split('.')[1];
+    final body = String.fromCharCodes(base64.decode(encodedBody));
+    return Id<User>(json.decode(body)['userId']);
+  }
```
Comment (JonasWanke) [inline lib/app/services/storage.dart]: We don't need to decode the token every time as we already store `userIdString`.
```suggestion
  Id<User> get userId => Id<User>(userIdString.getValue());
```

File: lib/app/hive.dart [hunk 3]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
-    ]);
-
-    final cache = HiveCache._(name, children, data);
-    await cache._collectGarbage();
-    return cache;
-  }
 
-  Future<void> _collectGarbage() async {
-    final usefulKeys = <String>{};
+/// An [Entity].
```
Comment (JonasWanke) [inline lib/app/hive.dart]: This comment isn't very helpful. Maybe explain what an `Entity` is or give a few examples?

File: lib/app/hive.dart [hunk 4]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+  Fetcher<dynamic> _getFetcherOfTypeId(int id) =>
+      _fetchers[id] ?? (throw UnsupportedError('Unknown type id $id.'));
+  Id<dynamic> _createIdOfTypeId(int typeId, String id) =>
+      _getFetcherOfTypeId(typeId)._createId(id);
+  IdCollection<dynamic> _createCollectionOfTypeId(
+          int typeId, String id, List<String> children) =>
+      _getFetcherOfTypeId(typeId)._createCollection(id, children);
+
+  void put<T extends Entity<T>>(T entity) {
+    // print('Entity: $entity with id ${entity.id.value}');
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
    logger.d('Hive: put ${entity.id} ($entity)');
```

File: lib/app/hive.dart [hunk 5]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
-
-    final cache = HiveCache._(name, children, data);
-    await cache._collectGarbage();
-    return cache;
-  }
 
-  Future<void> _collectGarbage() async {
-    final usefulKeys = <String>{};
+/// An [Entity].
+abstract class Entity<T extends Entity<T>> {
```
Comment (JonasWanke) [inline lib/app/hive.dart]: Can we mark `Entity` as immutable globally and remove individual `@immutable`'s on subclasses?

File: lib/app/hive.dart [hunk 6]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+}
 
-    // Remove all the non-useful entries.
-    final nonUsefulKeys = _data.keys.toSet().difference(usefulKeys);
-    await Future.wait([
-      _children.deleteAll(nonUsefulKeys),
-      _data.deleteAll(nonUsefulKeys),
-    ]);
-  }
+/// An [Id] that identifies an [Entity] among all other [Entity]s.
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
/// An [Id] that identifies an [Entity] among all other [Entity]s of the same type [T].
```

File: lib/app/hive.dart [hunk 7]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+class Id<T extends Entity<T>> {
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
@immutable
class Id<T extends Entity<T>> {
```

File: lib/app/hive.dart [hunk 8]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+  const Id(this.value);
```
Comment (JonasWanke) [inline lib/app/hive.dart]: Do we want to prevent empty IDs?

File: lib/app/hive.dart [hunk 9]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
-  Future<void> delete<T extends Entity>(Id<T> id) => _data.delete(id.id);
-  Future<void> clear() => Future.wait([_data.clear(), _children.clear()]);
+  @override
+  String toString() => value;
 }
 
-class Children extends HiveObject {
-  /// Map from stringified runtime types to lists of ids.
-  final Map<String, List<String>> _children = {};
+class AdapterForId extends TypeAdapter<Id<dynamic>> {
```
Comment (JonasWanke) [inline lib/app/hive.dart]: The name seems a bit odd. Maybe call it `IdAdapter` instead?
Also, this could be private.

File: lib/app/hive.dart [hunk 10]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+  const Entity();
 
-    void markAsUseful(String key) {
-      if (usefulKeys.contains(key)) {
-        return;
-      }
-      usefulKeys.add(key);
-      _children.get(key)?.getAllChildren()?.forEach(markAsUseful);
-    }
+  Id<T> get id;
```
Comment (JonasWanke) [inline lib/app/hive.dart]: What about passing the `id` as a constructor parameter? It shouldn't change and is known at instantiation anyway, right?

File: lib/app/hive.dart [hunk 11]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+  @override
+  Id<dynamic> read(BinaryReader reader) =>
+      HiveCache._createIdOfTypeId(reader.readInt(), reader.readString());
+}
 
-  Set<String> getAllChildren() =>
-      _children.values.reduce((a, b) => [...a, ...b]).toSet();
+/// A wrapper around multiple [Id]s.
+class IdCollection<T extends Entity<T>> implements Entity<IdCollection<T>> {
+  IdCollection({@required this.id, @required this.childrenIds});
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
  IdCollection({@required this.id, this.childrenIds = const []}) : assert(childrenIds != null);
```

File: lib/app/hive.dart [hunk 12]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
-  }
+  @override
+  final Id<IdCollection<T>> id;
+  final List<Id<T>> childrenIds;
+
+  int get typeId => HiveCache.typeIdByType<T>();
 }
 
-class ChildrenAdapter extends TypeAdapter<Children> {
+class AdapterForIdCollection extends TypeAdapter<IdCollection<dynamic>> {
```
Comment (JonasWanke) [inline lib/app/hive.dart]: The name seems a bit odd. Maybe call it `IdCollectionAdapter` instead?
Also, this could be private.

File: lib/app/hive.dart [hunk 13]
```diff
@@ -207,79 +262,80 @@ class RecurrenceRuleAdapter extends TypeAdapter<RecurrenceRule> {
...
+
+  static const typeContentType = 46;
+  static const typeContent = 57;
+  static const typeCourse = 58;
+  static const typeLesson = 59;
+
+  static const typeArticle = 56;
+
+  static const typeFile = 53;
+}
```
Comment (JonasWanke) [inline lib/app/hive.dart]: Do we really need the `type`-prefix everywhere?

File: lib/app/hive.dart [hunk 14]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+  IdCollection<dynamic> _createCollectionOfTypeId(
+          int typeId, String id, List<String> children) =>
+      _getFetcherOfTypeId(typeId)._createCollection(id, children);
+
+  void put<T extends Entity<T>>(T entity) {
+    // print('Entity: $entity with id ${entity.id.value}');
+    if (entity is IdCollection) {
+      _box.put(entity.id.value, entity);
+    }
+    _box.put(entity.id.value, entity);
```
Comment (JonasWanke) [inline lib/app/hive.dart]: Why `put` `IdCollection`'s twice?

File: lib/app/hive.dart [hunk 15]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+
+  final Future<T> Function(Id<T> id) fetch;
+
+  Id<T> _createId(String id) => Id<T>(id);
+  IdCollection<T> _createCollection(String id, List<String> children) {
+    return IdCollection<T>(
+      id: Id<IdCollection<T>>(id),
+      childrenIds: children.map((child) => Id<T>(child)).toList(),
+    );
+  }
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
  IdCollection<T> _createCollection(String id, List<String> childrenIds) {
    return IdCollection<T>(
      id: Id<IdCollection<T>>(id),
      childrenIds: childrenIds.map((id) => Id<T>(id)).toList(),
    );
  }
```

File: lib/app/hive.dart [hunk 16]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+}
 
-  @override
-  Id<T> read(BinaryReader reader) => Id<T>(reader.readString());
+// ignore: non_constant_identifier_names
+final HiveCache = HiveCacheImpl();
 
-  @override
-  void write(BinaryWriter writer, Id obj) => writer.writeString(obj.id);
+class Fetcher<T extends Entity<T>> {
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
@immutable
class Fetcher<T extends Entity<T>> {
```

File: lib/app/hive.dart [hunk 17]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+  Fetcher(this.fetch);
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
  Fetcher(this.fetch) : assert(fetch != null);
```

File: lib/app/hive.dart [hunk 18]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+    for (final fetcher in _fetchers.values) {
+      if (fetcher is Fetcher<T>) {
+        return fetcher.fetch(id);
+      }
+    }
+    throw UnsupportedError("We don't know how to fetch $T. Are you sure you "
+        'registered the type $T?');
+  }
+
+  Future<void> initialize() async => _box = await Hive.openBox('cache');
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
  Future<void> initialize() async {
    assert(_box == null, 'initialize was already called');
    _box = await Hive.openBox('cache');
  }
```

File: lib/app/hive.dart [hunk 19]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
-  Id<T> read(BinaryReader reader) => Id<T>(reader.readString());
+// ignore: non_constant_identifier_names
+final HiveCache = HiveCacheImpl();
 
-  @override
-  void write(BinaryWriter writer, Id obj) => writer.writeString(obj.id);
+class Fetcher<T extends Entity<T>> {
+  Fetcher(this.fetch);
+
+  final Future<T> Function(Id<T> id) fetch;
```
Comment (JonasWanke) [inline lib/app/hive.dart]: This could benefit from a `typedef`:
`typedef FetchFunction<E> = Future<E> Function(Id<E> id)`

File: lib/app/hive.dart (hunk 16 above)
Comment (JonasWanke) [inline lib/app/hive.dart]: As `T` must be an entity, I'd prefer to call it `E`. This applies to all `T`'s throughout this file relating to entities.

File: lib/app/hive.dart [hunk 20]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+      }
+    }
+    throw UnsupportedError("We don't know how to fetch $T. Are you sure you "
+        'registered the type $T?');
+  }
+
+  Future<void> initialize() async => _box = await Hive.openBox('cache');
+
+  void registerEntityType<T extends Entity<T>>(
+      int typeId, Future<T> Function(Id<T> id) fetch) {
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
      int typeId, FetchFunction<T> fetch) {
```
(See above comment for `FetchFunction`)

File: lib/app/hive.dart [hunk 21]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+    _fetchers[typeId] = Fetcher<T>(fetch);
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
    assert(_fetchers[typeId] == null, 'A fetcher with typeId $typeId is already registered');
    _fetchers[typeId] = Fetcher<T>(fetch);
```

File: lib/app/hive.dart [hunk 22]
```diff
@@ -15,163 +16,217 @@ import 'package:schulcloud/news/news.dart';
...
+        // ];
+      },
+      saveToCache: (items) {
+        // TODO(marcelgarus): Activate the cache.
+        return;
+
+        // final collection = IdCollection<T>(
+        //   id: _id,
+        //   childrenIds: items.map((item) => item.id).toList(),
+        // );
```
Comment (JonasWanke) [inline lib/app/hive.dart]: You could reuse `Fetcher._createCollection` from below.

File: lib/app/hive.dart [hunk 23]
```diff
@@ -207,79 +262,80 @@ class RecurrenceRuleAdapter extends TypeAdapter<RecurrenceRule> {
...
+    ..registerEntityType(TypeId.typeCourse, Course.fetch)
+    ..registerEntityType(TypeId.typeLesson, Lesson.fetch)
+    ..registerEntityType<Content>(
+      TypeId.typeContent,
+      (id) => throw UnsupportedError('Contents cannot be fetched by their id.'),
+    )
+    ..registerEntityType<File>(
+        TypeId.typeFile,
+        (id) => throw UnsupportedError('File need to know the type of their '
+            'owner, so they cannot be fetched by their id.'))
```
Comment (JonasWanke) [inline lib/app/hive.dart]:
```suggestion
        (id) => throw UnsupportedError('Files need to know the type of their '
            'owner, so they cannot be fetched by their id alone.'))
```

File: lib/app/utils.dart [hunk 24]
```diff
@@ -28,9 +28,37 @@ extension FancyContext on BuildContext {
...
+/// Gets some json from the server.
+Future<Map<String, dynamic>> fetchJsonFrom(String path) =>
+    services.network.get(path).json;
+
+/// Gets a json list from the server.
+Future<List<Map<String, dynamic>>> fetchJsonListFrom(
+  String path, {
+  // Surprise: The Calendar API's response is different from all others! Would
+  // be too easy otherwise ;)
+  bool wrappedInData = true,
```
Comment (JonasWanke) [inline lib/app/utils.dart]: I prefer the old name (`serviceIsPaginated`) as that conveys more semantic meaning and can soon be used to implement pagination.

File: lib/app/utils.dart [hunk 25]
```diff
@@ -28,9 +28,37 @@ extension FancyContext on BuildContext {
...
+  Map<String, String> parameters = const {},
+}) async {
+  var jsonData = jsonDecode(
+      (await services.network.get(path, parameters: parameters)).body);
```
Comment (JonasWanke) [inline lib/app/utils.dart]:
```suggestion
  var jsonData = await services.network.get(path, parameters: parameters).json;
```

File: lib/app/data.dart [hunk 26]
```diff
@@ -81,17 +93,71 @@ class User implements Entity {
   final List<Id<Role>> roles;
   bool get isTeacher => hasRole(Role.teacherName);
   bool hasRole(String name) {
-    // TODO(marcelgarus): Remove the hard-coded mapping and use runtime lookup when upgrading flutter_cached and flattening is supported
+    // TODO(marcelgarus): Remove the hard-coded mapping and use runtime lookup
+    // when upgrading flutter_cached and flattening is supported.
```
Comment (JonasWanke) [inline lib/app/data.dart]: TODO-suggestions from linters don't work when comments are broken across lines
```suggestion
    // TODO(marcelgarus): Remove the hard-coded mapping and use runtime lookup when upgrading flutter_cached and flattening is supported.
```

File: lib/app/utils.dart [hunk 27]
```diff
@@ -28,9 +28,37 @@ extension FancyContext on BuildContext {
...
+    services.network.get(path).json;
+
+/// Gets a json list from the server.
+Future<List<Map<String, dynamic>>> fetchJsonListFrom(
+  String path, {
+  // Surprise: The Calendar API's response is different from all others! Would
+  // be too easy otherwise ;)
+  bool wrappedInData = true,
+  Map<String, String> parameters = const {},
+}) async {
```
Comment (JonasWanke) [inline lib/app/utils.dart]: You could offer a `map` parameter as multiple calls look like the following:
```dart
(await fetchJsonListFrom('courses'))
  .map((data) => Course.fromJson(data))
  .toList(),
```

File: lib/app/widgets/menu.dart [hunk 28]
```diff
@@ -0,0 +1,182 @@
+import 'package:flutter/material.dart';
```
Comment (JonasWanke) [inline lib/app/widgets/menu.dart]: This file is obsolete and can be deleted

File: lib/assignment/data.dart [hunk 29]
```diff
@@ -105,22 +109,58 @@ class Assignment implements Entity {
...
+  bool get isArchived => archivedBy.contains(services.storage.userId);
 
   @HiveField(17)
   final bool teamSubmissions;
 
   @HiveField(18)
   final List<Id<File>> fileIds;
 
-  String get webUrl => scWebUrl('homework/${id.id}');
+  String get webUrl => scWebUrl('homework/${id.value}');
```
Comment (JonasWanke) [inline lib/assignment/data.dart]:
```suggestion
  String get webUrl => scWebUrl('homework/$id');
```

File: lib/assignment/data.dart [hunk 30]
```diff
@@ -105,22 +109,58 @@ class Assignment implements Entity {
...
   String get submissionWebUrl => '$webUrl#activetabid=submission';
+
+  @override
+  int compareTo(Assignment other) {
+    return other.id.value.compareTo(id.value);
+  }
```
Comment (JonasWanke) [inline lib/assignment/data.dart]: Is this really necessary?

File: lib/assignment/widgets/assignment_details_screen.dart [hunk 31]
```diff
@@ -52,9 +51,7 @@ class _AssignmentDetailsScreenState extends State<AssignmentDetailsScreen>
                       ? s.assignment_assignmentDetails_unarchive
                       : s.assignment_assignmentDetails_archive,
                   onPressed: () {
-                    services
-                        .get<AssignmentBloc>()
-                        .update(assignment, isArchived: !assignment.isArchived);
+                    assignment.update(isArchived: !assignment.isArchived);
                   },
```
Comment (JonasWanke) [inline lib/assignment/widgets/assignment_details_screen.dart]: Can be an expression body

File: lib/calendar/bloc.dart [hunk 32]
```diff
@@ -12,36 +12,19 @@ import 'data.dart';
...
     // 2. Implement your own logic to filter them. Have fun 😊
-    final allEvents = fetchEvents()..fetch();
+    final allEvents = services.storage.root.events.controller;
     return allEvents.updates.map((u) {
       if (!u.hasData) {
         return u;
       }
 
-      return CacheUpdate(
+      return CacheUpdate.raw(
```
Comment (JonasWanke) [inline lib/calendar/bloc.dart]: I think we can now use `CacheController.map` instead of directly working on a stream of `CacheUpdate`s

File: lib/course/data.dart [hunk 33]
```diff
@@ -19,7 +20,16 @@ class Course implements Entity {
         assert(name != null),
         assert(description != null),
         assert(teachers != null),
-        assert(color != null);
+        assert(color != null),
+        lessons = LazyIds<Lesson>(
+          collectionId: 'lessons of course $id',
+          fetcher: () async => (await fetchJsonListFrom('lessons?courseId=$id'))
+              .map((data) => Lesson.fromJson(data)),
```
Comment (JonasWanke) [inline lib/course/data.dart]: What about a static fetcher method on `Lesson` where you can provide `courseId` as an optional parameter? This would hide implementation details

File: lib/file/data.dart [hunk 34]
```diff
@@ -6,29 +6,42 @@ import 'package:time_machine/time_machine.dart';
...
-    @required this.isDirectory,
     @required this.parent,
-    this.size,
+    @required this.isDirectory,
+    @required this.mimeType,
+    @required this.size,
   })  : assert(id != null),
         assert(name != null),
         assert(owner != null),
         assert(owner is Id<User> || owner is Id<Course>),
```
Comment (JonasWanke) [inline lib/file/data.dart]: Seems like some asserts are missing

File: lib/file/data.dart [hunk 35]
```diff
@@ -6,29 +6,42 @@ import 'package:time_machine/time_machine.dart';
...
+          },
+        );
 
   File.fromJson(Map<String, dynamic> data)
       : this(
-          id: Id(data['_id']),
+          id: Id<File>(data['_id']),
           name: data['name'],
-          mimeType: data['type'],
+          mimeType: data['mimeType'],
```
Comment (JonasWanke) [inline lib/file/data.dart]: The field `mimeType` doesn't exist.
```suggestion
          mimeType: data['type'],
```

File: lib/file/data.dart [hunk 36]
```diff
@@ -6,29 +6,42 @@ import 'package:time_machine/time_machine.dart';
...
+          fetcher: () async {
+            final jsonData = await fetchJsonListFrom(
+              'fileStorage',
+              wrappedInData: false,
+              parameters: {
+                'owner': owner.value,
+                'parent': id.toString(),
+              },
+            );
+            return File.fromJsonList(jsonData);
```
Comment (JonasWanke) [inline lib/file/data.dart]: We could reuse `fetchByOwner` by renaming it to `fetchList` and adding an optional `parentId` attribute

File: lib/news/widgets/dashboard_card.dart [hunk 37]
```diff
@@ -21,12 +20,12 @@ class NewsDashboardCard extends StatelessWidget {
...
           .push(MaterialPageRoute(builder: (context) => NewsScreen())),
       child: CachedRawBuilder<List<Article>>(
-        controller: services.get<NewsBloc>().fetchArticles(),
+        controller: services.storage.root.news.controller,
         builder: (context, update) {
           if (!update.hasData) {
             return Center(
               child: update.hasError
-                  ? Text(update.error.toString())
+                  ? ErrorBanner(update.error, update.stackTrace)
```
Comment (JonasWanke) [inline lib/news/widgets/dashboard_card.dart]: Does `ErrorBanner` really need to be wrapped in `Center`?

**Review by JonasWanke — CHANGES_REQUESTED** [review]
Looks good, just minor change requests. I'm looking forward to using this code 🙂

General question: Do we want to name `Id`-fields with an `Id`-suffix (e.g. `ownerId`, `parentId` when fetching files)?

**Review by JonasWanke — CHANGES_REQUESTED** [review]
Looks good, just minor change requests. I'm looking forward to using this code 🙂

General question: Do we want to name `Id`-fields with an `Id`-suffix (e.g. `ownerId`, `parentId` when fetching files)?

File: lib/app/chip.dart (hunk 1 above)
Comment (MarcelGarus) [reply lib/app/chip.dart]: It's more concise and still readable as-is, so I don't think it's necessary to change it back

File: lib/app/hive.dart (hunk 9 above)
Comment (MarcelGarus) [reply lib/app/hive.dart]: The Hive TypeAdapter interface will be redesigned "soon" to create adapters of the naming scheme `AdapterForType` because that plays along better with generics (for example, `AdapterForList<User>`).

**Comment by MarcelGarus** [comment]
Fixed the issues. A few notes:

- I also [filed a PR](https://github.com/hivedb/hive/issues/245) for fixing the casting of generic types in Hive. Once that is merged, we're able to actually enable caching. :shipit:
- Contrary to what we talked about offline, because of [this Hive issue](https://github.com/hivedb/hive/issues/236), our classes can't extend `Entity`. That's why they implement `Entity` now, just like before.
- Entity fields that reference another entity by its id are now suffixed with `Id`. How should we suffix `LazyIds` fields? For example, the `Root` entity contains `courses`, which is not a `List` of `Course`s. `courseIds` would also not be accurate because it's not a `List<Id<Course>>` as well – rather it contains the knowledge of how to obtain the ids of courses. I didn't come up with a great name, so they have no suffix for now.
- Still need to merge with master and apparently some linter issues prevail.

**Comment by MarcelGarus** [comment]
The Hive PR got merged, but a new version of hive_generator still needs to get published to pub.dev

**Comment by MarcelGarus** [comment]
…which will hopefully happen within the next week: https://github.com/hivedb/hive/pull/250

**Comment by janrenz** [comment]
Why not take hive vom git instead pub.dev for now?

**Comment by MarcelGarus** [comment]
@janrenz Good idea, we're using the package from Git now.
Let's get this merged! :shipit:

File: lib/app/hive.dart [hunk 38]
```diff
@@ -101,69 +112,67 @@ class AdapterForIdCollection extends TypeAdapter<IdCollection<dynamic>> {
...
-        // TODO(marcelgarus): Activate the cache.
-        return;
-
-        // final collection = IdCollection<T>(
-        //   id: _id,
-        //   childrenIds: items.map((item) => item.id).toList(),
-        // );
-        // HiveCache.put<IdCollection<T>>(collection);
-        // items.forEach(HiveCache.put);
+        // TODO(marcelgarus): Use Fetcher._createCollection
```
Comment (JonasWanke) [inline lib/app/hive.dart]: TODO

File: lib/app/services/api_network.dart [hunk 39]
```diff
@@ -0,0 +1,70 @@
...
+import 'package:http/http.dart' as http;
+import 'package:schulcloud/app/app.dart';
+
+import 'storage.dart';
+
+/// A service that offers making network request to the backend servers. If the
+/// user's token is stored in the authentication storage, the requests' headers
+/// are automatically enriched with the access token.
+@immutable
+class ApiNetworkService {
```
Comment (JonasWanke) [inline lib/app/services/api_network.dart]: Please cherry-pick d2e8206 onto this branch to fix JSON-encoding of request bodies

File: lib/app/utils.dart [hunk 40]
```diff
@@ -29,31 +29,20 @@ extension FancyContext on BuildContext {
...
-  // be too easy otherwise ;)
-  bool wrappedInData = true,
-  Map<String, String> parameters = const {},
-}) async {
-  var jsonData = jsonDecode(
-      (await services.network.get(path, parameters: parameters)).body);
-  if (wrappedInData) {
-    jsonData = jsonData['data'];
+  Future<dynamic> get json async => (await this).json;
+  Future<List<Map<String, dynamic>>> parsedJsonList({
```
Comment (JonasWanke) [inline lib/app/utils.dart]: Please rename this method to `parseJsonList`

File: lib/course/data.dart [hunk 41]
```diff
@@ -53,8 +51,9 @@ class Course implements Entity<Course> {
   @HiveField(2)
   final String description;
 
+  // TODO(marcelgarus): For now, we don't use a [List<Id<User>>] here, because you can't cast a [List<Id>] to a [List<Id<User>>] without knowing about the [Id]'s [cast] method, which causes Hive to not be able to serialize generic types.
   @HiveField(3)
-  final List<Id<User>> teachers;
+  final List<Id<User>> teacherIds;
```
Comment (JonasWanke) [inline lib/course/data.dart]: ‽

File: lib/course/data.dart [hunk 42]
```diff
@@ -85,7 +84,14 @@ class Lesson implements Entity<Lesson> {
         );
 
   static Future<Lesson> fetch(Id<Lesson> id) async =>
-      Lesson.fromJson(await fetchJsonFrom('lessons/$id'));
+      Lesson.fromJson(await services.api.get('lessons/$id').json);
+
+  static Future<List<Lesson>> fetchMultiple({Id<Course> courseId}) async {
```
Comment (JonasWanke) [inline lib/course/data.dart]: Please rename this to `fetchList`

**Review by JonasWanke — CHANGES_REQUESTED** [review]

**Review by JonasWanke — APPROVED** [review]

**Review by JonasWanke — APPROVED** [review]
