### PR TITLE
Handle failed demo sign in

### LINKED ISSUE #285: Invalid credentials not handled
Trying to sign in using wrong credentials keeps the `SignInForm` in an infinite loading state.

### PR DESCRIPTION
**Pull request by MarcelGarus**
**Closes: #285**

When signing in with the demo account fails, a `SnackBar` is now shown to the user, instead of the button just spinning endlessly.

**Screenshots**

image

### CODE REVIEW

**Review by JonasWanke — CHANGES_REQUESTED** [review]
Code looks good, but we should also hide the demo login if it isn't supported.

**Comment by MarcelGarus** [comment]
Done, N21 now shows no demo buttons anymore.

image

File: lib/main.dart [hunk 1]
```diff
@@ -113,24 +113,26 @@ Future<void> main({AppConfig appConfig = schulCloudAppConfig}) async {
...
-      userId.resolve().listen((user) {
-        // TODO(marcelgarus): Don't hardcode role id.
-        final isDemo = [
-          Id<Role>('0000d186816abba584714d00'), // demo general
-          Id<Role>('0000d186816abba584714d02'), // demo student
-          Id<Role>('0000d186816abba584714d03'), // demo teacher
-        ].any((demoRole) => user?.roleIds?.contains(demoRole) ?? false);
+      userStream?.dispose();
+      userStream = userId.resolve()
+        ..listen((user) {
```
Comment (JonasWanke) [inline lib/main.dart:122]: Can we just use `Stream.switchMap()` from <kbd>rxdart</kbd> here?

**Review by JonasWanke — CHANGES_REQUESTED** [review]

File: lib/main.dart (hunk 1 above)
Comment (MarcelGarus) [reply lib/main.dart:122]: I don't think so because afaik it doesn't allow us to dispose the previous stream when a new one arrives…
Otherwise, we could of course just do `userIdStream.map((userId) => userId.resolve()).switchMap()`.

**Review by JonasWanke — APPROVED** [review]
