### PR TITLE
Fix demo login

### LINKED ISSUE #95: Errors show at username/password fields if using demo login
**Describe the bug**
Errors show up below the username and password field when using the demo login.

**To Reproduce**
1. Log out, if you are logged in.
2. Click on "demo as student"
3. While logging in, an error is shown below the username and password fields.

**Expected behavior**
There should be no error shown.

### LINKED ISSUE #106: Change the logout icon
The logout icon isn't chosen very intuitively. We could e.g. use the icon from the old android app: https://fontawesome.com/icons/sign-out-alt?style=solid

### PR DESCRIPTION
**Pull request by ctiedt**
Fixes #95 
Fixes #106

The demo logins no longer show validation errors and a proper logout icon is used. Also, logging out works again.

### CODE REVIEW

File: lib/login/bloc.dart [hunk 1]
```diff
@@ -21,7 +25,10 @@ class Bloc {
 
   Future<void> login(String email, String password) async {
     if (!isEmailValid(email) || !isPasswordValid(password)) {
-      throw InvalidLoginSyntaxError();
+      throw InvalidLoginSyntaxError(
+        isEmailValid: isEmailValid(email),
+        isPasswordValid: isPasswordValid(password),
```
Comment (MarcelGarus) [inline lib/login/bloc.dart]: We execute the regex check twice here. I think it's more elegant to do
```dart
final emailValid = isEmailValid(email);
final passwordValid = isPasswordValid(password);
if (!emailValid || !passwordValid) {
  throw InvalidLoginSyntaxError(isEmailValid: emailValid, isPasswordValid: passwordValid);
}
```

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

**Comment by MarcelGarus** [comment]
Now, when you had a failed login and continue to correct your email into a valid one, the error message doesn't disappear as soon as the email is correct again because the `_isEmailValid` and `_isPasswordValid` fields only get updated when trying to login 😕
That should be changed.

**Comment by ctiedt** [comment]
> Now, when you had a failed login and continue to correct your email into a valid one, the error message doesn't disappear as soon as the email is correct again because the `_isEmailValid` and `_isPasswordValid` fields only get updated when trying to login confused
> That should be changed.

We should probably create a new issue to debate how this should be handled, as the current solution does not really allow for an elegant way to show an error while entering an invalid email address and not show one when the demo buttons are used.

**Review by MarcelGarus — APPROVED** [review]
