### PR TITLE
News DashboardCard improvements

### LINKED ISSUE #115: Limit NewsDashboardCard to the 3 most recent entries
Either limit the list on UI side or wait for marcelgarus/flutter_cached#3

### LINKED ISSUE #154: Add news DashboardCard empty state

### LINKED ISSUE #158: News on dashboard should be sorted
**Describe the bug**
At the moment, news appear to not be sorted in any way. They should be sorted by date, the newest ones first.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by JonasWanke**
**Fixes: #158, fixes: #115, fixes: #154**

- This also improves the article preview design inside the card (align baselines, less emphasized text, bigger text preview with less whitespace)

image

### CODE REVIEW

File: lib/app/utils.dart [hunk 1]
```diff
@@ -46,6 +46,10 @@ String formatFileSize(int bytes) {
   return '${(bytes / power).toStringAsFixed(index == 0 ? 0 : 1)} ${units[index]}';
 }
 
+extension PowerfulString on String {
```
Comment (MarcelGarus) [inline lib/app/utils.dart]:
```suggestion
extension Legen...daryString on String {
```

Comment (MarcelGarus) [reply lib/app/utils.dart]: Or, to fix the syntax:
```suggestion
extension LegendaryString on String {
```

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

**Review by MarcelGarus — APPROVED** [review]
