### PR TITLE
Fix course names overflowing on file screen

### LINKED ISSUE #140: Course screen has overflowing items
image

### LINKED ISSUE #142: Course names overflow on the file screen
image

### PR DESCRIPTION
**Pull request by MarcelGarus**
#160 is more important and should be merged first.

**Fixes: #140, fixes: #142**

### CODE REVIEW

File: lib/course/widgets/courses_screen.dart [hunk 1]
```diff
@@ -25,12 +25,14 @@ class CoursesScreen extends StatelessWidget {
...
               SliverPadding(
                 padding: EdgeInsets.fromLTRB(16, 8, 16, 16),
-                sliver: SliverGrid.count(
-                  childAspectRatio: 1.5,
-                  crossAxisCount: 2,
-                  children: <Widget>[
-                    for (var course in courses) CourseCard(course: course),
-                  ],
+                sliver: SliverList(
+                  delegate: SliverChildListDelegate([
```
Comment (JonasWanke) [inline lib/course/widgets/courses_screen.dart]: Can we use a SliverChildBuilderDelegate instead?

**Review by JonasWanke — CHANGES_REQUESTED** [review]
The code is mostly fine, but I don't like the design of `CourseCard`s. There is horizontal padding by both `FancyCard` and `ListTile`, too much vertical padding inside cards and the colored rect on the left side looks misplaced

**Comment by janrenz** [comment]
Should we additionally use this: 
https://pub.dev/packages/auto_size_text#-readme-tab-
Tested locally, looks good and will work with long texts

**Comment by MarcelGarus** [comment]
I addressed all of Jonas' changes.
@janrenz For now, the courses just display the text in one line, as can be seen in the screenshot below. I think having different text sizes for the courses on the course overview list is a bit jarring to users.
Funny you should mention the `auto_size_text` package though — I already contributed to it and its run by the same guy who created Hive 😄

image

**Comment by MarcelGarus** [comment]
Now even with teacher names:

image

File: lib/course/bloc.dart [hunk 2]
```diff
@@ -37,12 +40,21 @@ class CourseBloc {
...
       loadFromCache: () => storage.cache.getChildrenOfType<User>(course.id),
       fetcher: () => Future.wait([
         for (final teacherId in course.teachers)
-          userFetcher.fetchUser(teacherId, course.id).fetch()
+          () async {
+            final userController = userFetcher.fetchUser(teacherId, course.id);
+            unawaited(userController.fetch());
+            final firstUpdate = await userController.updates
+                .firstWhere((update) => update.hasData, orElse: () => null);
+            // debugger(when: firstUpdate.hasData || firstUpdate.hasError);
```
Comment (JonasWanke) [inline lib/course/bloc.dart]:
```suggestion
```

File: lib/course/bloc.dart [hunk 3]
```diff
@@ -1,6 +1,9 @@
+import 'dart:developer';
+
```
Comment (JonasWanke) [inline lib/course/bloc.dart]:
```suggestion
```

File: lib/course/data.dart [hunk 4]
```diff
@@ -40,7 +40,7 @@ class Course implements Entity {
   @HiveField(2)
   final String description;
 
-  // For now, we don't use a [List<Id<User>>] here, because you can't cast a
+  // TODO(marcelgarus): For now, we don't use a [List<Id<User>>] here, because you can't cast a
   // [List<Id>] to a [List<Id<User>>] without knowing about the [Id]'s [cast]
   // method, which causes Hive to not be able to serialize generic types.
```
Comment (JonasWanke) [inline lib/course/data.dart]:
```suggestion
  // TODO(marcelgarus): For now, we don't use a [List<Id<User>>] here, because you can't cast a [List<Id>] to a [List<Id<User>>] without knowing about the [Id]'s [cast] method, which causes Hive to not be able to serialize generic types.
```

**Review by JonasWanke — CHANGES_REQUESTED** [review]

**Review by JonasWanke — APPROVED** [review]
