### PR TITLE
Use time machine throughout the project

### LINKED ISSUE #117: Use time_machine throughout the project
In many places, we simply parse the incorrect server times via `DateTime.parse`, which results in them being wrong locally as well. We can use the calendar module's code and use `Instant`s.
https://github.com/schul-cloud/schulcloud-flutter/blob/master/lib/calendar/data.dart#L143-L160

Also, formatting of dates and times for the user could be improved in many places. Maybe even switch between relative and absolute values?

### PR DESCRIPTION
**Pull request by JonasWanke**
**Please merge #135 first!**

Fixes: #117

Also fixes `NewsDashboardCard`: Multiple courses are merged into one entry by adding `==` to `Id`.

### CODE REVIEW

File: lib/app/datetime_utils.dart [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+}
+
+extension ApiCorrection on Instant {
+  // analyzer doesn't notice we use this field in serverTimeToActual()
+  // ignore: unused_field
+  static final _serverDateTimeZone = DateTimeZoneProviders.defaultProvider
+      .getDateTimeZoneSync('Europe/Berlin');
+
+  Instant serverTimeToActual() {
+    // The Calendar API uses tricky obfuscation: Times are said to be in UTC,
```
Comment (MarcelGarus) [inline lib/app/datetime_utils.dart]: The complete API times are garbage, not just the Calendar API 😅

File: lib/assignment/data.dart [hunk 2]
```diff
@@ -33,14 +34,15 @@ class Assignment implements Entity, Comparable {
           teacherId: data['teacherId'],
           name: data['name'],
           description: data['description'],
-          availableDate:
-              DateTime.tryParse(data['availableDate']) ?? DateTime.now(),
-          dueDate: DateTime.parse(data['dueDate']),
+          availableAt: (data['availableDate'] as String).parseApiInstant(),
```
Comment (MarcelGarus) [inline lib/assignment/data.dart:37]: What if `data['availableDate']` is `null`?

File: lib/assignment/data.dart [hunk 3]
```diff
@@ -33,14 +34,15 @@ class Assignment implements Entity, Comparable {
...
+          dueDate: (data['dueDate'] as String).parseApiInstant(),
```
Comment (MarcelGarus) [inline lib/assignment/data.dart:38]: Same here

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

File: lib/assignment/data.dart (hunk 2 above)
Comment (MarcelGarus) [reply lib/assignment/data.dart:37]: Come to think of it, that should better be handled somewhere higher up

File: lib/assignment/data.dart (hunk 3 above)
Comment (MarcelGarus) [reply lib/assignment/data.dart:38]: Come to think of it, that should better be handled somewhere higher up

**Review by MarcelGarus — APPROVED** [review]
